site_name: Combatting Bias
# repo_name: "combattingbias/combattingbias.huygens.knaw.nl/"
# repo_url: "https://github.com/combattingbias/combattingbias.huygens.knaw.nl/"
site_url: "https://combattingbias.huygens.knaw.nl/"

theme:
  name: material
  logo: static/img/logo/combattingbias.png
  favicon: static/img/logo/combattingbias-icon.png
  icon:
    logo: static/img/logo/combattingbias.png
  features:
    # Navigation fundamentals
    - navigation.instant     # Fast page loading
    - navigation.tracking    # URL updates with anchor targets
    # - navigation.instant.progress  # Show loading progress
    
    # Primary navigation setup
    - navigation.tabs       # Top-level sections as tabs
    - navigation.sections   # Sections in sidebar
    - navigation.expand     # Expand all sections by default
    
    # Navigation enhancements
    - navigation.path       # Breadcrumbs
    - navigation.top        # Back to top button
    - navigation.prune      # Reduce HTML size
    - toc.integrate        # Table of contents in navigation
    
    # Search enhancements
    - search.suggest       # Search suggestions

plugins:
  - search

nav:
 - Home: index.md
 - About:
      - The Project: about/mission.md
      - Ethical Commitments: about/ethicalcommitments.md
      - Project CV: about/project_cv.md
      - Team: 
        - Core Team: team/team.md
        - Partner Projects: team/partners/partnerprojects.md
        - Advisors: team/partners/advisors.md
 - Bias:
    - On Bias: bias/onbias.md
 
 - "Resources and Publications": 
   - "Resources": resourcesandpublications/resources.md
   - "Publications": resourcesandpublications/publications.md
 - "News":
      - "Combatting Bias Together! A Reflection on our May Events": news/mayevents.md
      - "Uncovering Shared yet Troubled Pasts (Event)": news/shared-yet-troubled-pasts.md
      - "Prisoners of the Past: Reflections on Bias in the Dutch East India Company Historian’s Craft ": news/historicalbias.md
      - "Towards Creating Meaningful Infrastructures for Colonial Archives": news/meaningfulinfrastructuresforcolonialarchives.md
      - "Reflecting on Bias: Lessons from the VOC Data Experience": news/voc_bias.md
      - "‘I’ am here! The necessity of acknowledging the historian in scholarship.": news/positionality.md
      - "Resource List": news/resourcelist.md
      - "Kickoff": news/kickoff.md
 - "Contact": contact/contact.md
markdown_extensions:
  - toc:
      permalink: True
  - admonition
  - smarty
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.magiclink
  - pymdownx.details
  - footnotes
  - attr_list #for links in new tab
plugins:
  - search # necessary for search to work
  - git-revision-date-localized
  - mkdocs-jupyter
extra_css:
  - stylesheets/extra.css
extra:
#   social:
#     - icon: material/web
#       name: Website
#       link: https://globalise.huygens.knaw.nl/
  generator: false
copyright: <p>
  <a rel="license" href="http://creativecommons.org/licenses/by-sa/4.0/"><img alt="Creative Commons License"
  style="border-width:0" src="https://licensebuttons.net/i/l/by-sa/transparent/ff/ff/ff/88x31.png" /></a><br/>
  The Combatting Bias project is financed by the <a href="https://nwo.nl" target="_top">Dutch Research Council (NWO)</a> via the <a href="https://tdcc.nl" target="_top">Thematic Digital Competence Centre Social Sciences & Humanities (TDCC-SSH)</a>. File id ICT.TDCC.001.001.
  <br>
  Information on this static website is licensed under a <a rel="license"
  href="http://creativecommons.org/licenses/by-sa/4.0/">Creative Commons BY-SA 4.0 International License</a>.
  </p>
  
