site_name: Combatting Bias project
repo_name: "combattingbias/combattingbias.huygens.knaw.nl/"
repo_url: "https://github.com/combattingbias/combattingbias.huygens.knaw.nl/"

theme:
  name: material
  # logo: static/img/logo/globalise_g.svg
  # favicon: static/img/logo/globalise_g.svg
  icon:
    # logo: material/flask
  features:
    # - navigation.instant
    - navigation.tracking
    - navigation.sections
    - navigation.path
    - navigation.top

nav:
  - Home: index.md
  #- About: about.md
  - "Ongoing experiments":
      - "Transcriptions Viewer": experiments/htr-viewer.md
      - "Places Visualization": experiments/places-visualization.md
      - "Word Embeddings": experiments/GLOBALISE_Word2Vec_Lab.ipynb
  - "Completed experiments":
      - "General Missives Search Interface": experiments/blacklab-search-interface-general-missives.md
      - "Text-Fabric Serialization of General Missives": experiments/text-fabric-general-missives.md
  #    - "Word Embeddings": experiments/word-embeddings.md
  -  "About"
  -  "Team"
  -  "Partners"
  -  "Resources"
  -  "Publications"
  -  "News"
  -  "Blog"
  -  "FAQ"
  -  "Contact"
markdown_extensions:
  - toc:
      permalink: True
  - admonition
  - smarty
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.magiclink
  - pymdownx.details
  - footnotes
plugins:
  - search # necessary for search to work
  - git-revision-date-localized
  - mkdocs-jupyter
extra_css:
  - stylesheets/extra.css
extra:
  social:
    - icon: material/web
      name: Website
      link: https://globalise.huygens.knaw.nl/
  generator: false
copyright: <p>
  <a rel="license" href="http://creativecommons.org/licenses/by-sa/4.0/"><img alt="Creative Commons License"
  style="border-width:0" src="https://licensebuttons.net/i/l/by-sa/transparent/ff/ff/ff/88x31.png" /></a><br/>
  The Combatting Bias project is financed by the Dutch Research Council (NWO) via the Thematic Digital Competence Centre Social Sciences & Humanities (TDCC-SSH). File id ICT.TDCC.001.001.
  <br>
  Information on this static website is licensed under a <a rel="license"
  href="http://creativecommons.org/licenses/by-sa/4.0/">Creative Commons BY-SA 4.0 International License</a>.
  </p>
